import { GLOBAL_DEFAULT_TITLE } from '@mtbird/core';

export default function Head() {
  return (
    <>
      <title>{GLOBAL_DEFAULT_TITLE}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
